"""Curriculum registry: the single source of truth for every page.

Navigation (core/navigation.py), page headers (core/page.py), search
(app_pages/resources/search.py), the progress tracker and docs/curriculum.md
are all generated from MODULES. To add a module, add one Module entry here and
create its page file.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Module:
    id: str
    file: str
    group: str
    title_ar: str
    title_en: str
    icon: str
    description: str
    objectives: tuple[str, ...] = ()
    prereqs: tuple[str, ...] = ()
    difficulty: str = "مبتدئ"
    minutes: int = 30
    keywords: tuple[str, ...] = ()
    lab: str = ""
    dataset: str = ""
    kind: str = "lesson"  # lesson | lab | project | resource | start
    tracked: bool = True  # counts toward progress percentage

    @property
    def label(self) -> str:
        return f"{self.title_ar} · {self.title_en}"


GROUPS: dict[str, str] = {
    "start": "ابدأ هنا · Start Here",
    "foundations": "أسس البيانات · Data Foundations",
    "quality": "جودة البيانات · Data Quality",
    "cleaning": "تنظيف البيانات · Data Cleaning",
    "eda": "التحليل الاستكشافي · EDA",
    "statistics": "الإحصاء · Statistics",
    "ml": "الخصائص وتعلّم الآلة · Features & ML",
    "mining": "التنقيب في البيانات · Data Mining",
    "modern": "علم البيانات الحديث · Modern Data Science",
    "labs": "المختبرات · Labs",
    "projects": "المشاريع · Projects",
    "practice": "الممارسة المهنية · Professional Practice",
    "resources": "الموارد · Resources",
}

_M = Module

MODULES: tuple[Module, ...] = (
    # ------------------------------------------------------------------ start
    _M("home", "app_pages/start/home.py", "start", "الرئيسية", "Home", ":material/home:",
       "الصفحة الرئيسية: خريطة المقرر، مسارات التعلّم، والتقدّم.", kind="start", tracked=False,
       keywords=("roadmap", "خريطة", "بداية")),
    _M("what_is_ds", "app_pages/start/what_is_ds.py", "start", "ما هو علم البيانات؟", "What is Data Science?",
       ":material/school:",
       "تعريف علم البيانات وعلاقته بالإحصاء وتعلّم الآلة والتنقيب وذكاء الأعمال وهندسة البيانات.",
       objectives=("التمييز بين Data Science وData Analysis وData Analytics.",
                   "فهم التداخل بين Statistics وMachine Learning وData Mining.",
                   "ربط كل مجال بنوع الأسئلة والمخرجات التي ينتجها."),
       difficulty="مبتدئ", minutes=35,
       keywords=("data science", "statistics", "machine learning", "AI", "BI", "data engineering",
                 "generative ai", "data analytics", "تحليل", "ذكاء اصطناعي")),
    _M("workflows", "app_pages/start/workflows.py", "start", "دورة حياة المشروع", "Workflows & Lifecycle",
       ":material/route:",
       "CRISP-DM وOSEMN وKDD ودورة حياة ML الحديثة، مع Workflow جامع يعتمده المقرر.",
       objectives=("شرح مراحل CRISP-DM وOSEMN وKDD.", "مقارنة الأطر وبيان نقاط قوتها.",
                   "استخدام Workflow جامع يربط الجودة بالتحليل والتوثيق."),
       prereqs=("what_is_ds",), minutes=30,
       keywords=("CRISP-DM", "OSEMN", "KDD", "lifecycle", "MLOps", "workflow")),
    _M("course_guide", "app_pages/start/course_guide.py", "start", "دليل المقرر", "Course Guide",
       ":material/menu_book:",
       "كيف تستخدم المنصة: المستويات، أنماط التعلّم، خريطة المتطلبات السابقة، والمسارات المقترحة.",
       minutes=10, kind="start", tracked=False,
       keywords=("guide", "prerequisites", "مسار", "levels", "مستويات")),

    # ------------------------------------------------------------ foundations
    _M("data_concepts", "app_pages/foundations/data_concepts.py", "foundations", "مفاهيم البيانات",
       "Data Concepts", ":material/dataset:",
       "Dataset وObservation وVariable وFeature وTarget وSchema وMetadata وData Dictionary.",
       objectives=("تعريف مكونات الـDataset بدقة.", "التمييز بين Feature وTarget وIdentifier.",
                   "قراءة Schema وبناء Data Dictionary."),
       prereqs=("what_is_ds",), minutes=35, dataset="customers_clean",
       keywords=("dataset", "observation", "feature", "target", "schema", "metadata", "primary key",
                 "data dictionary", "entity")),
    _M("variable_types", "app_pages/foundations/variable_types.py", "foundations", "أنواع البيانات والمتغيرات",
       "Variable & Data Types", ":material/category:",
       "Structured وSemi-structured وUnstructured؛ Numerical وCategorical؛ Cross-sectional وTime Series وPanel.",
       objectives=("تصنيف المتغيرات إلى Continuous/Discrete/Nominal/Ordinal/Binary.",
                   "التمييز بين تصاميم البيانات Cross-sectional/Time Series/Panel.",
                   "استخدام Variable Inspector لاستنتاج النوع الدلالي."),
       prereqs=("data_concepts",), minutes=40, lab="Variable Inspector", dataset="all",
       keywords=("numerical", "categorical", "ordinal", "nominal", "panel", "time series",
                 "cross-sectional", "semi-structured", "json", "types")),
    _M("data_sources", "app_pages/foundations/data_sources.py", "foundations", "مصادر البيانات وجمعها",
       "Data Sources & Collection", ":material/database:",
       "CSV وExcel وJSON وParquet وSQL وAPIs والاستبيانات والتجارب والبيانات الإدارية وStreaming.",
       objectives=("مقارنة مصادر البيانات من حيث البنية والموثوقية والخصوصية.",
                   "معرفة المشكلات النموذجية لكل مصدر.", "قراءة البيانات من عدة صيغ باستخدام pandas."),
       prereqs=("variable_types",), minutes=30,
       keywords=("csv", "excel", "json", "parquet", "sql", "api", "web scraping", "survey", "streaming",
                 "logs", "iot")),
    _M("importing_data", "app_pages/foundations/importing_data.py", "foundations", "مختبر استيراد البيانات",
       "Importing Data Lab", ":material/upload_file:",
       "رفع CSV/Excel/JSON بأمان مع فحص الترميز والفاصل والأعمدة المكررة والتحذيرات الأولية.",
       objectives=("استيراد الملفات بأمان والتحقق من سلامتها.", "قراءة ملخص أولي: Shape وDtypes وMemory.",
                   "تفسير التحذيرات الأولية قبل أي تحليل."),
       prereqs=("data_sources",), minutes=25, kind="lab", lab="Importing Data Lab",
       keywords=("upload", "read_csv", "encoding", "delimiter", "dtypes", "memory", "استيراد")),

    # ---------------------------------------------------------------- quality
    _M("quality_dimensions", "app_pages/quality/quality_dimensions.py", "quality", "أبعاد جودة البيانات",
       "Data Quality Dimensions", ":material/verified:",
       "Completeness وAccuracy وConsistency وValidity وUniqueness وTimeliness مع Dashboard شفافة الأوزان.",
       objectives=("تعريف أبعاد جودة البيانات وقياس كل بعد.", "بناء Quality Score بصيغة وأوزان معلنة.",
                   "تفسير الـsub-scores بدل رقم واحد غامض."),
       prereqs=("data_concepts",), minutes=40, lab="Data Quality Dashboard", dataset="customers_raw",
       keywords=("data quality", "completeness", "accuracy", "consistency", "validity", "uniqueness",
                 "timeliness", "integrity", "score", "جودة")),
    _M("data_validation", "app_pages/quality/data_validation.py", "quality", "التحقق من صحة البيانات",
       "Data Validation", ":material/rule:",
       "Schema/Type/Range/Category/Regex/Cross-field/Referential/Temporal rules، وأدوات Pandera وPydantic وGX.",
       objectives=("كتابة قواعد تحقق قابلة للتنفيذ.", "التمييز بين أنواع قواعد التحقق.",
                   "اختيار أداة التحقق المناسبة (Pandera, Pydantic, GX Core)."),
       prereqs=("quality_dimensions",), difficulty="متوسط", minutes=45, lab="Rule Builder",
       dataset="customers_raw",
       keywords=("validation", "schema", "pandera", "pydantic", "great expectations", "regex",
                 "business rules", "referential integrity", "تحقق")),
    _M("missing_values", "app_pages/quality/missing_values.py", "quality", "القيم المفقودة: الفهم والتشخيص",
       "Missing Values: Mechanisms & Diagnostics", ":material/help_center:",
       "NaN وNone والقيم الدلالية المفقودة، آليات MCAR/MAR/MNAR بالمحاكاة، وتشخيص الأنماط.",
       objectives=("اكتشاف القيم المفقودة الصريحة والدلالية (Sentinels).",
                   "فهم MCAR/MAR/MNAR وتأثيرها على التقديرات.",
                   "تشخيص نمط الفقد عبر المجموعات والزمن وPanel."),
       prereqs=("variable_types", "quality_dimensions"), difficulty="متوسط", minutes=60,
       lab="MCAR/MAR/MNAR Simulator", dataset="survey",
       keywords=("missing", "nan", "mcar", "mar", "mnar", "sentinel", "little", "missingness",
                 "مفقودة", "heatmap")),
    _M("missing_treatment", "app_pages/quality/missing_treatment.py", "quality", "معالجة القيم المفقودة",
       "Missing Data Treatment", ":material/build:",
       "الحذف، Mean/Median/Mode، Interpolation، KNN، Regression، Iterative وMultiple Imputation.",
       objectives=("مقارنة طرق المعالجة من حيث الافتراضات والتحيّز.",
                   "قياس أثر الـImputation على التوزيع والتباين والعلاقات.",
                   "فهم Multiple Imputation وقواعد Rubin."),
       prereqs=("missing_values",), difficulty="متقدم", minutes=60, lab="Imputation Experiment",
       dataset="survey",
       keywords=("imputation", "knn", "iterative", "multiple imputation", "rubin", "listwise",
                 "interpolation", "ffill", "تعويض")),
    _M("duplicates", "app_pages/quality/duplicates.py", "quality", "التكرارات", "Duplicates",
       ":material/content_copy:",
       "Exact وPartial وNear duplicates، والتكرار المشروع في Panel والمعاملات.",
       objectives=("استخدام duplicated() وdrop_duplicates() مع subset وkeep.",
                   "التمييز بين التكرار الخاطئ والتكرار المشروع.", "اكتشاف Near duplicates."),
       prereqs=("data_concepts",), minutes=30, dataset="customers_raw",
       keywords=("duplicates", "duplicated", "drop_duplicates", "near duplicate", "key", "تكرار")),
    _M("outliers", "app_pages/quality/outliers.py", "quality", "القيم الشاذة والحالات غير الطبيعية",
       "Outliers & Anomalies", ":material/scatter_plot:",
       "IQR وZ-score وModified Z وMAD، ثم Isolation Forest وLOF وOne-Class SVM، مع أداة القرار.",
       objectives=("التمييز بين Outlier وAnomaly وInfluential observation.",
                   "تطبيق الطرق الإحصائية والنموذجية للكشف.",
                   "اتخاذ قرار مبرر: Keep/Investigate/Correct/Transform/Cap/Remove."),
       prereqs=("univariate",), difficulty="متوسط", minutes=55, lab="Outlier Decision Tool",
       dataset="customers_raw",
       keywords=("outlier", "anomaly", "iqr", "z-score", "mad", "isolation forest", "lof", "winsorize",
                 "شاذة")),
    _M("consistency", "app_pages/quality/consistency.py", "quality", "القيم غير الصالحة ومشكلات الاتساق",
       "Invalid Values & Consistency", ":material/difference:",
       "القيم المستحيلة، الوحدات المختلطة، التناقض بين الحقول، والتسميات غير المتسقة.",
       objectives=("اكتشاف القيم المستحيلة منطقيًا.", "اكتشاف تناقضات Cross-field والوحدات.",
                   "ربط الإحصاء بمعرفة المجال Domain Knowledge."),
       prereqs=("quality_dimensions",), minutes=35, dataset="customers_raw",
       keywords=("invalid", "consistency", "units", "impossible", "cross-field", "domain", "اتساق")),

    # --------------------------------------------------------------- cleaning
    _M("numerical_cleaning", "app_pages/cleaning/numerical_cleaning.py", "cleaning", "تنظيف البيانات الرقمية",
       "Numerical Data Cleaning", ":material/functions:",
       "القيم السالبة/الصفرية المستحيلة، Infinity، الأخطاء العشرية، الوحدات، الدقة، الالتواء.",
       objectives=("تحويل الأعمدة النصية إلى أرقام بأمان.", "اكتشاف أخطاء الوحدات والفواصل العشرية.",
                   "تقييم الالتواء والذيول الثقيلة."),
       prereqs=("consistency",), minutes=35, dataset="customers_raw",
       keywords=("to_numeric", "infinity", "units", "skewness", "precision", "rounding", "رقمية")),
    _M("categorical_data", "app_pages/cleaning/categorical_data.py", "cleaning", "البيانات الفئوية",
       "Categorical Data", ":material/abc:",
       "Nominal/Ordinal، High cardinality، الفئات النادرة، الأخطاء الإملائية والمسافات وحالة الأحرف.",
       objectives=("توحيد التسميات Label Standardization.", "معالجة الفئات النادرة وHigh cardinality.",
                   "استخدام Categorical dtype المرتب."),
       prereqs=("variable_types",), minutes=35, dataset="customers_raw",
       keywords=("categorical", "labels", "cardinality", "rare categories", "typos", "whitespace",
                 "فئوية")),
    _M("encoding", "app_pages/cleaning/encoding.py", "cleaning", "ترميز المتغيرات", "Encoding",
       ":material/data_object:",
       "Label/Ordinal/One-Hot/Frequency/Target/Hashing وEmbeddings مع مخاطر Leakage.",
       objectives=("اختيار الترميز المناسب لكل نوع متغير.", "فهم أثر الترميز على الأبعاد.",
                   "تطبيق Target Encoding دون Leakage."),
       prereqs=("categorical_data", "splitting"), difficulty="متوسط", minutes=40,
       keywords=("one-hot", "target encoding", "ordinal", "hashing", "embedding", "ترميز")),
    _M("datetime_data", "app_pages/cleaning/datetime_data.py", "cleaning", "بيانات التاريخ والوقت",
       "Date & Time Data", ":material/calendar_month:",
       "Parsing والمناطق الزمنية وResampling وLag/Lead وRolling والموسمية وCalendar features.",
       objectives=("تحويل النصوص إلى datetime بأمان.", "بناء Lag وRolling features.",
                   "اكتشاف الطوابع الزمنية المفقودة وResampling."),
       prereqs=("variable_types",), minutes=40, dataset="daily_sales",
       keywords=("datetime", "timezone", "resample", "lag", "rolling", "seasonality", "تاريخ")),
    _M("text_data", "app_pages/cleaning/text_data.py", "cleaning", "البيانات النصية", "Text Data",
       ":material/text_fields:",
       "Cleaning وTokenization وStopwords وStemming وN-grams وBag of Words وTF-IDF وEmbeddings.",
       objectives=("تنظيف النص وتطبيعه.", "تحويل النص إلى Features عبر BoW وTF-IDF.",
                   "فهم فكرة Embeddings وTransformers دون تخصص NLP كامل."),
       prereqs=("categorical_data",), difficulty="متوسط", minutes=40, dataset="reviews",
       keywords=("text", "tokenization", "tf-idf", "bag of words", "n-grams", "embeddings", "نص")),
    _M("transformations", "app_pages/cleaning/transformations.py", "cleaning", "التحويلات والقياس",
       "Transformations & Scaling", ":material/transform:",
       "Log وBox-Cox وYeo-Johnson وWinsorization وStandardization وMin-Max وRobust scaling مع Animations.",
       objectives=("اختيار التحويل المناسب للالتواء.", "التمييز بين Standardization وNormalization.",
                   "معرفة متى نحتاج Scaling ومتى لا نحتاجه."),
       prereqs=("univariate",), difficulty="متوسط", minutes=45, lab="Before/After Animation",
       keywords=("log", "box-cox", "yeo-johnson", "standardization", "normalization", "min-max",
                 "robust scaler", "scaling", "تحويل")),

    # -------------------------------------------------------------------- eda
    _M("eda_foundations", "app_pages/eda/eda_foundations.py", "eda", "أسس التحليل الاستكشافي",
       "EDA Foundations", ":material/explore:",
       "الفرق بين Descriptive وExploratory وConfirmatory وDiagnostic وPredictive، وEDA Workflow.",
       objectives=("وضع EDA في سياق دورة التحليل.", "اتباع Workflow منظم للاستكشاف.",
                   "تجنب تحويل EDA إلى صيد p-values."),
       prereqs=("quality_dimensions",), minutes=25,
       keywords=("eda", "exploratory", "confirmatory", "descriptive", "استكشافي")),
    _M("univariate", "app_pages/eda/univariate.py", "eda", "التحليل أحادي المتغير", "Univariate Analysis",
       ":material/bar_chart:",
       "Mean وMedian وVariance وQuantiles وSkewness وKurtosis وHistogram وECDF وBoxplot.",
       objectives=("حساب وتفسير مقاييس النزعة المركزية والتشتت.", "قراءة Histogram وECDF وBoxplot.",
                   "فهم أثر القيم المتطرفة على المتوسط."),
       prereqs=("eda_foundations",), minutes=45, dataset="all",
       keywords=("mean", "median", "variance", "skewness", "kurtosis", "histogram", "ecdf", "boxplot")),
    _M("bivariate", "app_pages/eda/bivariate.py", "eda", "التحليل ثنائي المتغير", "Bivariate Analysis",
       ":material/ssid_chart:",
       "Scatter وCorrelation وGroup summaries وViolin وContingency tables.",
       objectives=("اختيار أداة التحليل حسب نوعي المتغيرين.", "تفسير الارتباط وحدوده.",
                   "قراءة Crosstab والنسب الشرطية."),
       prereqs=("univariate",), minutes=40, dataset="all",
       keywords=("correlation", "scatter", "crosstab", "violin", "group by", "pearson", "spearman")),
    _M("multivariate", "app_pages/eda/multivariate.py", "eda", "التحليل متعدد المتغيرات",
       "Multivariate Analysis", ":material/grid_view:",
       "Correlation matrix وPairplot وParallel coordinates وPCA وMulticollinearity (VIF).",
       objectives=("قراءة مصفوفة الارتباط والـHeatmap.", "تشخيص Multicollinearity عبر VIF.",
                   "استكشاف البنية متعددة الأبعاد بصريًا."),
       prereqs=("bivariate",), difficulty="متوسط", minutes=40, dataset="all",
       keywords=("correlation matrix", "heatmap", "pairplot", "parallel coordinates", "vif",
                 "multicollinearity")),
    _M("visualization", "app_pages/eda/visualization.py", "eda", "التصوير البياني",
       "Data Visualization", ":material/insights:",
       "اختيار الرسم الصحيح، ومحدد الرسوم، وأخطاء التصوير المضللة.",
       objectives=("اختيار نوع الرسم حسب السؤال ونوع البيانات.", "اكتشاف الرسوم المضللة.",
                   "تصميم رسم واضح ومتاح للجميع."),
       prereqs=("univariate",), minutes=40, lab="Chart Selector",
       keywords=("chart", "visualization", "misleading", "truncated axis", "overplotting", "رسم")),

    # ------------------------------------------------------------- statistics
    _M("stat_foundations", "app_pages/statistics/stat_foundations.py", "statistics", "أسس الاستدلال الإحصائي",
       "Statistical Foundations", ":material/functions:",
       "Population/Sample وSampling variability وStandard Error وConfidence Interval وEffect size.",
       objectives=("التمييز بين Parameter وStatistic.", "فهم Standard Error وتوزيع المعاينة.",
                   "تفسير فترة الثقة تفسيرًا صحيحًا."),
       prereqs=("univariate",), difficulty="متوسط", minutes=50, lab="CI Coverage Animation",
       keywords=("population", "sample", "standard error", "confidence interval", "clt",
                 "effect size", "sampling distribution", "استدلال")),
    _M("hypothesis_tests", "app_pages/statistics/hypothesis_tests.py", "statistics", "الاختبارات الإحصائية",
       "Statistical Tests", ":material/science:",
       "نظام اختيار الاختبار، t-tests وANOVA وChi-square والارتباط والاختبارات اللامعلمية مع Effect size.",
       objectives=("اختيار الاختبار حسب السؤال والتصميم ونوع المتغير.",
                   "تفسير p-value وCI وEffect size معًا.", "فحص الافتراضات قبل التفسير."),
       prereqs=("stat_foundations",), difficulty="متقدم", minutes=60, lab="Test Selector & Runner",
       dataset="students",
       keywords=("t-test", "anova", "chi-square", "mann-whitney", "wilcoxon", "kruskal", "shapiro",
                 "levene", "p-value", "hypothesis", "اختبار")),

    # --------------------------------------------------------------------- ml
    _M("feature_engineering", "app_pages/ml/feature_engineering.py", "ml", "هندسة الخصائص واختيارها",
       "Feature Engineering & Selection", ":material/construction:",
       "Interactions وRatios وBinning وAggregations وLag features، ثم Filter/Wrapper/Embedded selection.",
       objectives=("إنشاء خصائص مفيدة مبنية على المجال.", "تطبيق طرق اختيار الخصائص.",
                   "استخدام Permutation importance بشكل صحيح."),
       prereqs=("multivariate", "encoding"), difficulty="متوسط", minutes=50, dataset="credit",
       keywords=("feature engineering", "feature selection", "interaction", "binning", "lasso",
                 "permutation importance", "خصائص")),
    _M("ml_foundations", "app_pages/ml/ml_foundations.py", "ml", "أسس تعلّم الآلة", "ML Foundations",
       ":material/model_training:",
       "Supervised وUnsupervised وSemi/Self-supervised، الانحدار والتصنيف، Bias-Variance.",
       objectives=("تصنيف مسائل التعلم.", "فهم Bias-Variance وOverfitting بصريًا.",
                   "ربط ML بالإحصاء والتنقيب."),
       prereqs=("stat_foundations",), difficulty="متوسط", minutes=40,
       keywords=("supervised", "unsupervised", "regression", "classification", "overfitting",
                 "bias variance", "تعلم الآلة")),
    _M("splitting", "app_pages/ml/splitting.py", "ml", "التقسيم والتحقق المتقاطع",
       "Train/Validation/Test & CV", ":material/call_split:",
       "Holdout وK-Fold وStratified وGroup K-Fold وTime Series Split وNested CV.",
       objectives=("فهم دور Train/Validation/Test.", "اختيار مخطط التقسيم المناسب للتصميم.",
                   "معرفة لماذا لا يصلح Random Split دائمًا."),
       prereqs=("ml_foundations",), difficulty="متوسط", minutes=40, lab="Split Animation",
       keywords=("train test split", "cross validation", "k-fold", "stratified", "group k-fold",
                 "time series split", "nested cv")),
    _M("data_leakage", "app_pages/ml/data_leakage.py", "ml", "تسرّب البيانات", "Data Leakage",
       ":material/warning:",
       "Target/Preprocessing/Temporal/Group leakage مع Demo لنموذج «ممتاز» زائف.",
       objectives=("اكتشاف أنواع التسرب الستة.", "إعادة إنتاج نتيجة مضخمة بسبب التسرب ثم إصلاحها.",
                   "استخدام Pipeline لمنع Preprocessing leakage."),
       prereqs=("splitting",), difficulty="متقدم", minutes=45, lab="Leakage Demo", dataset="credit",
       keywords=("leakage", "target leakage", "contamination", "pipeline", "temporal", "تسرب")),
    _M("model_evaluation", "app_pages/ml/model_evaluation.py", "ml", "تقييم النماذج", "Model Evaluation",
       ":material/leaderboard:",
       "MAE/RMSE/R² وAccuracy/Precision/Recall/F1 وROC-AUC وPR curve والعتبة وعدم التوازن.",
       objectives=("اختيار المقياس المناسب للمسألة.", "فهم أثر العتبة Threshold.",
                   "معرفة لماذا تضلل Accuracy في البيانات غير المتوازنة."),
       prereqs=("splitting",), difficulty="متوسط", minutes=45, lab="Threshold Explorer", dataset="credit",
       keywords=("accuracy", "precision", "recall", "f1", "roc", "auc", "pr curve", "rmse", "mae",
                 "confusion matrix", "imbalance")),

    # ----------------------------------------------------------------- mining
    _M("data_mining", "app_pages/mining/data_mining.py", "mining", "التنقيب وقواعد الارتباط",
       "Data Mining & Association Rules", ":material/hub:",
       "Pattern discovery وKDD وقواعد الارتباط Apriori: Support وConfidence وLift.",
       objectives=("وضع Data Mining في علاقته بالإحصاء وML.", "حساب Support وConfidence وLift.",
                   "تفسير القواعد بحذر وتجنب القواعد التافهة."),
       prereqs=("eda_foundations",), difficulty="متوسط", minutes=45, lab="Apriori Explorer",
       dataset="baskets",
       keywords=("data mining", "association rules", "apriori", "support", "confidence", "lift",
                 "market basket", "تنقيب")),
    _M("clustering", "app_pages/mining/clustering.py", "mining", "التجميع", "Clustering",
       ":material/bubble_chart:",
       "K-Means مع Animation لحركة المراكز، Hierarchical وDBSCAN، وSilhouette.",
       objectives=("فهم خوارزمية K-Means خطوة بخطوة.", "اختيار عدد العناقيد بأدلة متعددة.",
                   "مقارنة K-Means وDBSCAN وHierarchical."),
       prereqs=("transformations",), difficulty="متوسط", minutes=45, lab="K-Means Animation",
       dataset="customers_clean",
       keywords=("clustering", "k-means", "dbscan", "hierarchical", "silhouette", "elbow", "تجميع")),
    _M("anomaly_detection", "app_pages/mining/anomaly_detection.py", "mining", "اكتشاف الحالات الشاذة",
       "Anomaly Detection", ":material/troubleshoot:",
       "Isolation Forest (مع Animation للعزل)، LOF، One-Class SVM، Robust covariance.",
       objectives=("فهم فكرة العزل في Isolation Forest.", "ضبط contamination وتفسير النتائج.",
                   "مقارنة الخوارزميات على نفس البيانات."),
       prereqs=("outliers",), difficulty="متقدم", minutes=40, lab="Isolation Animation",
       keywords=("anomaly", "isolation forest", "lof", "one-class svm", "elliptic envelope",
                 "contamination")),
    _M("dim_reduction", "app_pages/mining/dim_reduction.py", "mining", "تقليل الأبعاد",
       "Dimensionality Reduction", ":material/compress:",
       "PCA وExplained variance وLoadings، مع مقدمة إلى t-SNE/UMAP.",
       objectives=("فهم PCA هندسيًا ورياضيًا.", "قراءة Scree plot والـLoadings.",
                   "معرفة حدود t-SNE/UMAP في التفسير."),
       prereqs=("multivariate", "transformations"), difficulty="متقدم", minutes=40, dataset="wine",
       keywords=("pca", "dimensionality reduction", "explained variance", "loadings", "t-sne", "umap")),

    # ----------------------------------------------------------------- modern
    _M("traditional_vs_modern", "app_pages/modern/traditional_vs_modern.py", "modern",
       "التقليدي مقابل الحديث", "Traditional vs Modern DS", ":material/sync_alt:",
       "Manual وAutomated وHybrid workflows، وفلسفة الإنسان في الحلقة.",
       objectives=("مقارنة سير العمل اليدوي والآلي والهجين.", "معرفة ما يمكن أتمتته وما لا ينبغي.",
                   "تبني فلسفة Hybrid."),
       prereqs=("quality_dimensions", "eda_foundations"), minutes=30,
       keywords=("manual", "automated", "hybrid", "automation", "modern")),
    _M("automated_eda", "app_pages/modern/automated_eda.py", "modern", "الاستكشاف الآلي",
       "Automated EDA & Discovery", ":material/auto_awesome:",
       "Profiling آلي، Schema/Semantic type inference، Relationship discovery، وأدوات fg-data-profiling وSweetviz وskimpy.",
       objectives=("فهم ما تفعله أدوات الـProfiling.", "تشغيل Profiler مدمج وقراءة نتائجه.",
                   "تقييم حدود الأدوات الآلية وحالة صيانتها."),
       prereqs=("traditional_vs_modern", "univariate"), difficulty="متوسط", minutes=35,
       keywords=("automated eda", "profiling", "ydata", "fg-data-profiling", "sweetviz", "skimpy",
                 "semantic type", "schema inference", "discovery")),
    _M("automated_cleaning", "app_pages/modern/automated_cleaning.py", "modern", "التنظيف الآلي",
       "Automated Data Cleaning", ":material/cleaning_services:",
       "Rule-based وStatistical وML-based وAI-assisted cleaning مع Issue detector يشرح «لماذا؟».",
       objectives=("مقارنة أساليب التنظيف الآلي.", "قراءة تقرير المشكلات: Severity وEvidence وWhy.",
                   "فهم لماذا لا يُنفذ حذف غير قابل للتراجع آليًا."),
       prereqs=("automated_eda", "missing_treatment", "outliers"), difficulty="متوسط", minutes=35,
       keywords=("automated cleaning", "rule-based", "issues", "severity", "suggestion")),
    _M("automl", "app_pages/modern/automl.py", "modern", "التعلّم الآلي المؤتمت", "AutoML",
       ":material/precision_manufacturing:",
       "Mini-AutoML حقيقي: بحث في النماذج والمعاملات مع CV وLeaderboard، وأدوات FLAML وAutoGluon وTPOT.",
       objectives=("فهم مكونات AutoML: Search space وBudget وValidation.", "تشغيل Mini-AutoML وقراءة Leaderboard.",
                   "معرفة مخاطر AutoML: Leakage وOverfitting للـValidation."),
       prereqs=("model_evaluation", "data_leakage"), difficulty="متقدم", minutes=40, lab="Mini-AutoML",
       dataset="credit",
       keywords=("automl", "flaml", "autogluon", "tpot", "hyperparameter", "leaderboard")),
    _M("observability", "app_pages/modern/observability.py", "modern", "مراقبة البيانات والانجراف",
       "Data Observability & Drift", ":material/monitoring:",
       "Freshness وSchema drift وData drift (PSI/KS) وLineage وData contracts.",
       objectives=("فهم أعمدة Data observability.", "قياس Data drift بـPSI وKS.",
                   "كتابة Data contract بسيط."),
       prereqs=("data_validation",), difficulty="متوسط", minutes=35, lab="Drift Simulator",
       keywords=("observability", "drift", "psi", "ks test", "schema drift", "lineage",
                 "data contract", "freshness", "evidently")),
    _M("ai_assisted", "app_pages/modern/ai_assisted.py", "modern", "علم البيانات بمساعدة الذكاء الاصطناعي",
       "AI-Assisted Data Science", ":material/smart_toy:",
       "LLMs وCopilots وNL-to-code وData Agents، ومخاطر الهلوسة والخصوصية وإعادة الإنتاج.",
       objectives=("فهم أنماط استخدام LLMs في التحليل.", "تدقيق مخرجات AI واكتشاف أخطائها.",
                   "تصميم سير عمل آمن لوكيل بيانات Data Agent."),
       prereqs=("traditional_vs_modern",), difficulty="متوسط", minutes=40, lab="AI Output Audit",
       keywords=("llm", "copilot", "data agent", "nl to code", "hallucination", "ai", "semantic layer",
                 "ذكاء اصطناعي")),
    _M("human_in_loop", "app_pages/modern/human_in_loop.py", "modern", "الإنسان في الحلقة",
       "Human-in-the-Loop", ":material/handshake:",
       "Automation should assist judgment, not erase judgment — مع مخطط تفاعلي وسجل قرارات.",
       objectives=("تطبيق دورة Detection→Review→Decision→Validation→Documentation.",
                   "توثيق القرارات بشكل قابل للتدقيق.", "تحديد نقاط التدخل البشري الإلزامية."),
       prereqs=("automated_cleaning",), minutes=25,
       keywords=("human in the loop", "review", "decision log", "judgment", "إنسان")),

    # ------------------------------------------------------------------- labs
    _M("dataset_explorer", "app_pages/labs/dataset_explorer.py", "labs", "مستكشف البيانات",
       "Dataset Explorer", ":material/data_exploration:",
       "ارفع ملفًا أو اختر Dataset مدمجة واحصل على تشخيص كامل مع توصيات.",
       prereqs=("importing_data",), minutes=20, kind="lab", lab="Dataset Explorer", dataset="all",
       keywords=("explorer", "profile", "upload", "summary", "مستكشف")),
    _M("missing_lab", "app_pages/labs/missing_lab.py", "labs", "مختبر القيم المفقودة", "Missing Data Lab",
       ":material/lab_profile:",
       "شخّص الفقد ثم قارن طرق التعويض على بيانات حقيقية مع إخفاء قيم معروفة لقياس الخطأ.",
       prereqs=("missing_treatment",), difficulty="متوسط", minutes=30, kind="lab", lab="Missing Data Lab",
       dataset="all", keywords=("missing lab", "imputation", "rmse", "mask")),
    _M("outlier_lab", "app_pages/labs/outlier_lab.py", "labs", "مختبر القيم الشاذة", "Outlier Lab",
       ":material/experiment:",
       "قارن IQR وZ وModified Z وIsolation Forest وLOF على نفس البيانات مع مصفوفة الاتفاق.",
       prereqs=("outliers",), difficulty="متوسط", minutes=30, kind="lab", lab="Outlier Lab", dataset="all",
       keywords=("outlier lab", "agreement", "iqr", "isolation forest")),
    _M("cleaning_lab", "app_pages/labs/cleaning_lab.py", "labs", "مختبر التنظيف اليدوي",
       "Manual Cleaning Lab", ":material/cleaning_services:",
       "نظّف Dataset التحدي خطوة بخطوة وقارن قبل/بعد في جودة البيانات.",
       prereqs=("consistency", "categorical_data"), difficulty="متوسط", minutes=40, kind="lab",
       lab="Before vs After", dataset="customers_raw",
       keywords=("cleaning lab", "before after", "manual")),
    _M("eda_lab", "app_pages/labs/eda_lab.py", "labs", "مختبر التحليل الاستكشافي", "EDA Lab",
       ":material/query_stats:",
       "استكشف أي Dataset بالرسوم أحادية وثنائية ومتعددة المتغيرات مع تفسير تلقائي.",
       prereqs=("bivariate",), minutes=30, kind="lab", lab="EDA Lab", dataset="all",
       keywords=("eda lab", "explore", "charts")),
    _M("pipeline_builder", "app_pages/labs/pipeline_builder.py", "labs", "باني خط المعالجة",
       "Pipeline Builder", ":material/account_tree:",
       "اختر استراتيجيات المعالجة، اعرض المخطط، شغّل، وحمّل كود Python المكافئ.",
       prereqs=("transformations", "encoding", "missing_treatment"), difficulty="متوسط", minutes=35,
       kind="lab", lab="Pipeline Builder", dataset="all",
       keywords=("pipeline", "builder", "generated code", "sklearn pipeline")),
    _M("automation_lab", "app_pages/labs/automation_lab.py", "labs", "مختبر اليدوي مقابل الآلي",
       "Manual vs Automated vs Hybrid Lab", ":material/sync_alt:",
       "نفس البيانات بثلاثة أنماط: أنت تقرر، أو المنصة، أو المنصة تقترح وأنت تعتمد.",
       prereqs=("automated_cleaning",), difficulty="متوسط", minutes=35, kind="lab", lab="Hybrid Lab",
       dataset="all", keywords=("hybrid", "manual", "automated", "human review")),
    _M("auto_report", "app_pages/labs/auto_report.py", "labs", "التقرير الآلي",
       "Automated Analysis Report", ":material/description:",
       "تقرير تحليلي آلي يميّز بين Detected issue وPotential issue وRecommendation، قابل للتحميل.",
       prereqs=("automated_eda",), minutes=15, kind="lab", lab="Report Generator", dataset="all",
       keywords=("report", "automated report", "markdown", "html", "download")),

    # --------------------------------------------------------------- projects
    _M("case_studies", "app_pages/projects/case_studies.py", "projects", "دراسات الحالة", "Case Studies",
       ":material/work:",
       "ست دراسات حالة كاملة: العملاء، التجزئة، الاستبيان، السلاسل الزمنية، Panel، والنصوص.",
       prereqs=("eda_lab",), difficulty="متوسط", minutes=90, kind="project",
       keywords=("case study", "retail", "survey", "time series", "panel", "text", "customer")),
    _M("data_story", "app_pages/projects/data_story.py", "projects", "قصة البيانات", "Interactive Data Story",
       ":material/auto_stories:",
       "«وصلتنا Dataset خام من مؤسسة»: عشر محطات تكشف المشكلات تدريجيًا حتى التفسير النهائي.",
       prereqs=("data_leakage", "cleaning_lab"), difficulty="متوسط", minutes=45, kind="project",
       keywords=("story", "project", "end to end", "قصة")),
    _M("capstone", "app_pages/projects/capstone.py", "projects", "المشروع النهائي", "Capstone Project",
       ":material/workspace_premium:",
       "من Raw Data إلى تقرير نهائي: 14 مرحلة مع قائمة تحقق وتقرير قابل للتحميل.",
       prereqs=("data_story",), difficulty="متقدم", minutes=180, kind="project",
       keywords=("capstone", "final project", "report", "نهائي")),

    # --------------------------------------------------------------- practice
    _M("reproducibility", "app_pages/practice/reproducibility.py", "practice", "قابلية إعادة الإنتاج",
       "Reproducibility", ":material/replay:",
       "البيئات الافتراضية، requirements وpyproject، البذور العشوائية، Git، Pipelines، وتتبع التجارب.",
       objectives=("بناء مشروع قابل لإعادة الإنتاج.", "فهم Seeds وVersioning وData versioning.",
                   "التمييز بين Notebook وScript."),
       prereqs=("workflows",), minutes=30,
       keywords=("reproducibility", "venv", "uv", "requirements", "seed", "git", "dvc", "mlflow")),
    _M("ethics", "app_pages/practice/ethics.py", "practice", "أخلاقيات البيانات والخصوصية",
       "Data Ethics & Privacy", ":material/policy:",
       "الخصوصية، البيانات الحساسة، Minimization، التحيز والعدالة، الموافقة والاستخدام المسؤول.",
       objectives=("تحديد البيانات الحساسة وتقليلها.", "قياس فجوة عدالة بسيطة.",
                   "تطبيق قائمة استخدام مسؤول."),
       prereqs=("what_is_ds",), minutes=30,
       keywords=("ethics", "privacy", "fairness", "bias", "consent", "pii", "أخلاقيات", "خصوصية")),

    # -------------------------------------------------------------- resources
    _M("search", "app_pages/resources/search.py", "resources", "البحث", "Search", ":material/search:",
       "ابحث في الدروس والمسرد والموضوعات.", kind="resource", tracked=False,
       keywords=("search", "بحث")),
    _M("progress", "app_pages/resources/progress.py", "resources", "تقدّمي", "My Progress",
       ":material/trending_up:",
       "الدروس المكتملة ونتائج الاختبارات والمختبرات والمفضلة، مع تصدير واستيراد التقدم.",
       kind="resource", tracked=False, keywords=("progress", "bookmarks", "تقدم", "مفضلة")),
    _M("glossary", "app_pages/resources/glossary.py", "resources", "المسرد", "Glossary", ":material/book:",
       "مسرد عربي/إنجليزي قابل للبحث.", kind="resource", tracked=False,
       keywords=("glossary", "terms", "مسرد", "مصطلحات")),
    _M("cheat_sheets", "app_pages/resources/cheat_sheets.py", "resources", "أوراق المراجعة",
       "Cheat Sheets & Comparisons", ":material/receipt_long:",
       "أوراق مراجعة pandas/cleaning/stats وجداول مقارنة شاملة وأدوات قرار سريعة.",
       kind="resource", tracked=False,
       keywords=("cheat sheet", "comparison", "pandas", "decision", "مراجعة", "مقارنة")),
    _M("references", "app_pages/resources/references.py", "resources", "المراجع", "References",
       ":material/library_books:",
       "المصادر الرسمية والكتب والمقررات التي بُني عليها المحتوى.", kind="resource", tracked=False,
       keywords=("references", "sources", "books", "مراجع")),
    _M("about", "app_pages/resources/about.py", "resources", "عن المنصة", "About", ":material/info:",
       "عن المنصة والمطوّر والمنهجية التقنية.", kind="resource", tracked=False,
       keywords=("about", "author", "عن")),
)

_BY_ID: dict[str, Module] = {m.id: m for m in MODULES}


def get_module(module_id: str) -> Module:
    """Return a module by id, raising a clear error for typos."""
    try:
        return _BY_ID[module_id]
    except KeyError as exc:  # pragma: no cover - developer error
        raise KeyError(f"Unknown module id: {module_id!r}") from exc


def modules_in_group(group: str) -> list[Module]:
    return [m for m in MODULES if m.group == group]


def tracked_modules() -> list[Module]:
    return [m for m in MODULES if m.tracked]


def next_module(module_id: str) -> Module | None:
    """The next tracked module in curriculum order (skips resources)."""
    ids = [m.id for m in MODULES if m.tracked]
    if module_id not in ids:
        return None
    i = ids.index(module_id)
    return _BY_ID[ids[i + 1]] if i + 1 < len(ids) else None


ROADMAP: tuple[tuple[str, str, str], ...] = (
    ("Raw Data", "البيانات الخام", "data_concepts"),
    ("Data Collection", "جمع البيانات", "data_sources"),
    ("Data Understanding", "فهم البيانات", "variable_types"),
    ("Data Validation", "التحقق", "data_validation"),
    ("Data Quality", "الجودة", "quality_dimensions"),
    ("Data Cleaning", "التنظيف", "numerical_cleaning"),
    ("EDA", "الاستكشاف", "eda_foundations"),
    ("Statistics", "الإحصاء", "stat_foundations"),
    ("Feature Engineering", "هندسة الخصائص", "feature_engineering"),
    ("Data Mining", "التنقيب", "data_mining"),
    ("Machine Learning", "تعلّم الآلة", "ml_foundations"),
    ("Evaluation", "التقييم", "model_evaluation"),
    ("Interpretation", "التفسير", "hypothesis_tests"),
    ("Communication", "التواصل", "visualization"),
    ("Automation", "الأتمتة", "automated_eda"),
    ("AI-Assisted DS", "بمساعدة AI", "ai_assisted"),
)

LEARNING_PATHS: dict[str, dict] = {
    "foundations": {
        "title": "مسار الأساسيات",
        "desc": "للمبتدئ: من مفهوم البيانات حتى التحليل الاستكشافي.",
        "modules": ("what_is_ds", "data_concepts", "variable_types", "quality_dimensions",
                    "missing_values", "duplicates", "univariate", "bivariate", "visualization"),
    },
    "quality": {
        "title": "مسار جودة البيانات والتنظيف",
        "desc": "للمحلل: تشخيص المشكلات ومعالجتها بقرارات مبررة.",
        "modules": ("quality_dimensions", "data_validation", "missing_values", "missing_treatment",
                    "outliers", "consistency", "categorical_data", "transformations", "cleaning_lab",
                    "pipeline_builder"),
    },
    "ml": {
        "title": "مسار النمذجة",
        "desc": "للمتقدم: من الإحصاء إلى تقييم النماذج دون تسرّب.",
        "modules": ("stat_foundations", "hypothesis_tests", "feature_engineering", "ml_foundations",
                    "splitting", "data_leakage", "model_evaluation", "clustering", "automl"),
    },
    "modern": {
        "title": "مسار علم البيانات الحديث",
        "desc": "للباحث والممارس: الأتمتة والذكاء الاصطناعي مع الإنسان في الحلقة.",
        "modules": ("traditional_vs_modern", "automated_eda", "automated_cleaning", "observability",
                    "ai_assisted", "human_in_loop", "automation_lab", "reproducibility", "ethics"),
    },
}
