"""Generate docs/curriculum.md and docs/datasets.md from the registries, and
export the built-in datasets to data/synthetic/ as CSV.

Run:  python scripts/build_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from content.quizzes import QUIZZES  # noqa: E402
from core.curriculum import GROUPS, MODULES, get_module  # noqa: E402
from utils.datasets import DATASET_INFO, load_dataset  # noqa: E402


def curriculum_md() -> str:
    lines = ["# Curriculum map · خريطة المقرر", "",
             "Generated from `core/curriculum.py` by `scripts/build_docs.py` — do not edit by hand.", ""]
    for g, label in GROUPS.items():
        mods = [m for m in MODULES if m.group == g]
        lines += [f"## {label}", "",
                  "| Module | Prerequisites | Learning objectives | Practical lab | Quiz | Dataset | Difficulty | Minutes |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- |"]
        for m in mods:
            pre = ", ".join(get_module(p).title_en for p in m.prereqs) or "—"
            obj = "<br>".join(m.objectives) or m.description
            quiz = f"{len(QUIZZES[m.id])} questions" if m.id in QUIZZES else "—"
            lines.append(f"| **{m.title_en}**<br>{m.title_ar} | {pre} | {obj} | {m.lab or '—'} | {quiz} | {m.dataset or '—'} | "
                         f"{m.difficulty} | {m.minutes} |")
        lines.append("")
    return "\n".join(lines)


def datasets_md() -> str:
    lines = ["# Built-in datasets · مجموعات البيانات المدمجة", "",
             "All datasets are synthetic (fixed seeds, `utils/datasets.py`) or public and non-sensitive (scikit-learn Iris, Wine). "
             "CSV copies are in `data/synthetic/`. Generated by `scripts/build_docs.py`.", ""]
    for name, info in DATASET_INFO.items():
        df = load_dataset(name)
        lines += [f"## `{name}` — {info['title']}", "", f"- **Shape:** {df.shape[0]} × {df.shape[1]}",
                  f"- **Design:** {info['design']}", f"- **Purpose:** {info['purpose']}", "", "**Variables**", ""]
        lines += [f"- `{k}` — {v}" for k, v in info["variables"].items()]
        lines += ["", "**Intentional issues**", ""] + [f"- {i}" for i in info["issues"]]
        lines += ["", "**Suggested lessons:** " + ", ".join(get_module(m).title_en for m in info["lessons"]), ""]
    return "\n".join(lines)


def main() -> None:
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "curriculum.md").write_text(curriculum_md(), encoding="utf-8")
    (ROOT / "docs" / "datasets.md").write_text(datasets_md(), encoding="utf-8")
    out = ROOT / "data" / "synthetic"
    out.mkdir(parents=True, exist_ok=True)
    for name in DATASET_INFO:
        load_dataset(name).to_csv(out / f"{name}.csv", index=False, encoding="utf-8")
    print("docs/curriculum.md, docs/datasets.md and data/synthetic/*.csv written.")


if __name__ == "__main__":
    main()
